apiVersion: iam.aws.jet.crossplane.io/v1alpha2
kind: InstanceProfile
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha2/instanceprofile
  labels:
    testing.upbound.io/example-name: test_profile
  name: test-profile
spec:
  forProvider:
    roleSelector:
      matchLabels:
        testing.upbound.io/example-name: role

---

apiVersion: iam.aws.jet.crossplane.io/v1alpha2
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha2/instanceprofile
  labels:
    testing.upbound.io/example-name: role
  name: role
spec:
  forProvider:
    assumeRolePolicy: |
      {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Action": "sts:AssumeRole",
                  "Principal": {
                     "Service": "ec2.amazonaws.com"
                  },
                  "Effect": "Allow",
                  "Sid": ""
              }
          ]
      }
    path: /

---

