apiVersion: iam.aws.jet.crossplane.io/v1alpha2
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha2/policy
  labels:
    testing.upbound.io/example-name: policy
  name: policy
spec:
  forProvider:
    description: My test policy
    name: test_policy
    path: /
    policy: |-
      ${jsonencode({
          Version = "2012-10-17"
          Statement = [
            {
              Action = [
                "ec2:Describe*",
              ]
              Effect   = "Allow"
              Resource = "*"
            },
          ]
        })}

---

