apiVersion: iam.aws.jet.crossplane.io/v1alpha2
kind: RolePolicyAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha2/rolepolicyattachment
  labels:
    testing.upbound.io/example-name: test-attach
  name: test-attach
spec:
  forProvider:
    policyArnSelector:
      matchLabels:
        testing.upbound.io/example-name: policy
    roleSelector:
      matchLabels:
        testing.upbound.io/example-name: role

---

apiVersion: iam.aws.jet.crossplane.io/v1alpha2
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha2/rolepolicyattachment
  labels:
    testing.upbound.io/example-name: policy
  name: policy
spec:
  forProvider:
    description: A test policy
    name: test-policy
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Action": [
              "ec2:Describe*"
            ],
            "Effect": "Allow",
            "Resource": "*"
          }
        ]
      }

---

apiVersion: iam.aws.jet.crossplane.io/v1alpha2
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha2/rolepolicyattachment
  labels:
    testing.upbound.io/example-name: role
  name: role
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Action": "sts:AssumeRole",
            "Principal": {
              "Service": "ec2.amazonaws.com"
            },
            "Effect": "Allow",
            "Sid": ""
          }
        ]
      }

---

