apiVersion: iam.aws.jet.crossplane.io/v1alpha2
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha2/user
  labels:
    testing.upbound.io/example-name: lb
  name: lb
spec:
  forProvider:
    path: /system/
    tags:
      tag-key: tag-value

---

apiVersion: iam.aws.jet.crossplane.io/v1alpha2
kind: AccessKey
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha2/user
  labels:
    testing.upbound.io/example-name: lb
  name: lb
spec:
  forProvider:
    userSelector:
      matchLabels:
        testing.upbound.io/example-name: lb

---

