apiVersion: iam.aws.jet.crossplane.io/v1alpha2
kind: UserGroupMembership
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha2/usergroupmembership
  labels:
    testing.upbound.io/example-name: example1
  name: example1
spec:
  forProvider:
    groupRefs:
    - name: group1
    - name: group2
    userSelector:
      matchLabels:
        testing.upbound.io/example-name: user1

---

apiVersion: iam.aws.jet.crossplane.io/v1alpha2
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha2/usergroupmembership
  labels:
    testing.upbound.io/example-name: group1
  name: group1
spec:
  forProvider: {}

---

apiVersion: iam.aws.jet.crossplane.io/v1alpha2
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha2/usergroupmembership
  labels:
    testing.upbound.io/example-name: group2
  name: group2
spec:
  forProvider: {}

---

apiVersion: iam.aws.jet.crossplane.io/v1alpha2
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha2/usergroupmembership
  labels:
    testing.upbound.io/example-name: group3
  name: group3
spec:
  forProvider: {}

---

apiVersion: iam.aws.jet.crossplane.io/v1alpha2
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha2/usergroupmembership
  labels:
    testing.upbound.io/example-name: user1
  name: user1
spec:
  forProvider: {}

---

