apiVersion: elbv2.aws.jet.crossplane.io/v1alpha2
kind: LB
metadata:
  annotations:
    meta.upbound.io/example-id: elbv2/v1alpha2/lb
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    accessLogs:
    - bucketSelector:
        matchLabels:
          testing.upbound.io/example-name: lb_logs
      enabled: true
      prefix: test-lb
    enableDeletionProtection: true
    internal: false
    loadBalancerType: application
    name: test-lb-tf
    securityGroupRefs:
    - name: lb_sg
    subnetSelector:
      matchLabels:
        testing.upbound.io/example-name: 'public : subnet'
    tags:
      Environment: production

---

