apiVersion: elbv2.aws.jet.crossplane.io/v1alpha2
kind: LBListener
metadata:
  annotations:
    meta.upbound.io/example-id: elbv2/v1alpha2/lblistener
  labels:
    testing.upbound.io/example-name: front_end
  name: front-end
spec:
  forProvider:
    certificateArn: arn:aws:iam::187416307283:server-certificate/test_cert_rab3wuqwgja25ct3n4jdj2tzu4
    defaultAction:
    - targetGroupArnSelector:
        matchLabels:
          testing.upbound.io/example-name: front_end
      type: forward
    loadBalancerArnSelector:
      matchLabels:
        testing.upbound.io/example-name: front_end
    port: "443"
    protocol: HTTPS
    sslPolicy: ELBSecurityPolicy-2016-08

---

apiVersion: elbv2.aws.jet.crossplane.io/v1alpha2
kind: LB
metadata:
  annotations:
    meta.upbound.io/example-id: elbv2/v1alpha2/lblistener
  labels:
    testing.upbound.io/example-name: front_end
  name: front-end
spec:
  forProvider: {}

---

apiVersion: elbv2.aws.jet.crossplane.io/v1alpha2
kind: LBTargetGroup
metadata:
  annotations:
    meta.upbound.io/example-id: elbv2/v1alpha2/lblistener
  labels:
    testing.upbound.io/example-name: front_end
  name: front-end
spec:
  forProvider: {}

---

