apiVersion: elbv2.aws.jet.crossplane.io/v1alpha2
kind: LBTargetGroupAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: elbv2/v1alpha2/lbtargetgroupattachment
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    port: 80
    targetGroupArnSelector:
      matchLabels:
        testing.upbound.io/example-name: test
    targetId: ${aws_instance.test.id}

---

apiVersion: ec2.aws.jet.crossplane.io/v1alpha2
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: elbv2/v1alpha2/lbtargetgroupattachment
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider: {}

---

apiVersion: elbv2.aws.jet.crossplane.io/v1alpha2
kind: LBTargetGroup
metadata:
  annotations:
    meta.upbound.io/example-id: elbv2/v1alpha2/lbtargetgroupattachment
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider: {}

---

