apiVersion: elbv2.aws.jet.crossplane.io/v1alpha2
kind: LBTargetGroup
metadata:
  annotations:
    meta.upbound.io/example-id: elbv2/v1alpha2/lbtargetgroup
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    name: tf-example-lb-tg
    port: 80
    protocol: HTTP
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: main

---

apiVersion: ec2.aws.jet.crossplane.io/v1alpha2
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: elbv2/v1alpha2/lbtargetgroup
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16

---

