apiVersion: mq.aws.jet.crossplane.io/v1alpha2
kind: Broker
metadata:
  name: example
spec:
  forProvider:
    # Due to an existing Terrajet limitation, we cannot use "metadata.name" for "brokerName"
    # Details can be found in https://github.com/upbound/upjet/issues/280
    brokerName: example-broker
    region: us-west-1
    engineType: ActiveMQ
    engineVersion: 5.15.9
    hostInstanceType: mq.t2.micro
    user:
    - passwordSecretRef:
        key: password
        name: mq-secret
        namespace: crossplane-system
      username: admin