apiVersion: route53.aws.jet.crossplane.io/v1alpha2
kind: HealthCheck
metadata:
  annotations:
    meta.upbound.io/example-id: route53/v1alpha2/healthcheck
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    failureThreshold: "5"
    fqdn: example.com
    port: 80
    requestInterval: "30"
    resourcePath: /
    tags:
      Name: tf-test-health-check
    type: HTTP

---

