apiVersion: route53.aws.jet.crossplane.io/v1alpha2
kind: Zone
metadata:
  annotations:
    meta.upbound.io/example-id: route53/v1alpha2/zone
  labels:
    testing.upbound.io/example-name: primary
  name: primary
spec:
  forProvider:
    name: example.com

---

