apiVersion: kms.aws.jet.crossplane.io/v1alpha2
kind: Key
metadata:
  annotations:
    meta.upbound.io/example-id: kms/v1alpha2/key
  labels:
    testing.upbound.io/example-name: a
  name: a
spec:
  forProvider:
    deletionWindowInDays: 10
    description: KMS key 1

---

