apiVersion: s3.aws.jet.crossplane.io/v1alpha2
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: s3/v1alpha2/bucket
  labels:
    testing.upbound.io/example-name: b
  name: b
spec:
  forProvider:
    tags:
      Environment: Dev
      Name: My bucket

---

