apiVersion: ecrpublic.aws.jet.crossplane.io/v1alpha2
kind: Repository
metadata:
  annotations:
    meta.upbound.io/example-id: ecrpublic/v1alpha2/repository
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    catalogData:
    - aboutText: About Text
      architectures:
      - ARM
      description: Description
      logoImageBlob: ${filebase64(image.png)}
      operatingSystems:
      - Linux
      usageText: Usage Text
    provider: ${aws.us_east_1}

---

