apiVersion: rds.aws.jet.crossplane.io/v1alpha2
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1alpha2/instance
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    allocatedStorage: 10
    engine: mysql
    engineVersion: "5.7"
    instanceClass: db.t3.micro
    name: mydb
    parameterGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    skipFinalSnapshot: true
    username: foo

---

