apiVersion: rds.aws.jet.crossplane.io/v1alpha2
kind: ParameterGroup
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1alpha2/parametergroup
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    family: mysql5.6
    parameter:
    - name: character_set_server
      value: utf8
    - name: character_set_client
      value: utf8

---

