apiVersion: globalaccelerator.aws.jet.crossplane.io/v1alpha2
kind: EndpointGroup
metadata:
  annotations:
    meta.upbound.io/example-id: globalaccelerator/v1alpha2/endpointgroup
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    endpointConfiguration:
    - endpointId: ${aws_lb.example.arn}
      weight: 100
    listenerArnSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

