apiVersion: ec2.aws.jet.crossplane.io/v1alpha2
kind: EIP
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1alpha2/eip
  labels:
    testing.upbound.io/example-name: lb
  name: lb
spec:
  forProvider:
    instanceSelector:
      matchLabels:
        testing.upbound.io/example-name: web
    vpc: true

---

