apiVersion: ec2.aws.jet.crossplane.io/v1alpha2
kind: Route
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1alpha2/route
  labels:
    testing.upbound.io/example-name: r
  name: r
spec:
  forProvider:
    destinationCidrBlock: 10.0.1.0/22
    routeTableIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    vpcPeeringConnectionIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

