apiVersion: ec2.aws.jet.crossplane.io/v1alpha2
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1alpha2/securitygroup
  labels:
    testing.upbound.io/example-name: allow_tls
  name: allow-tls
spec:
  forProvider:
    description: Allow TLS inbound traffic
    name: allow_tls
    tags:
      Name: allow_tls
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: main

---

