apiVersion: ec2.aws.jet.crossplane.io/v1alpha2
kind: SecurityGroupRule
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1alpha2/securitygrouprule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    cidrBlocks:
    - ${aws_vpc.example.cidr_block}
    fromPort: 0
    ipv6CidrBlocks:
    - ${aws_vpc.example.ipv6_cidr_block}
    protocol: tcp
    securityGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    toPort: 65535
    type: ingress

---

