apiVersion: ec2.aws.jet.crossplane.io/v1alpha2
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1alpha2/subnet
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    cidrBlock: 10.0.1.0/24
    tags:
      Name: Main
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: main

---

