apiVersion: ec2.aws.jet.crossplane.io/v1alpha2
kind: VPCEndpoint
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1alpha2/vpcendpoint
  labels:
    testing.upbound.io/example-name: s3
  name: s3
spec:
  forProvider:
    serviceName: com.amazonaws.us-west-2.s3
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: main

---

