apiVersion: ec2.aws.jet.crossplane.io/v1alpha2
kind: VPCPeeringConnection
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1alpha2/vpcpeeringconnection
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    peerOwnerId: ${var.peer_owner_id}
    peerVpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: bar
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo

---

