apiVersion: eks.aws.jet.crossplane.io/v1alpha2
kind: IdentityProviderConfig
metadata:
  annotations:
    meta.upbound.io/example-id: eks/v1alpha2/identityproviderconfig
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    clusterNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    oidc:
    - clientId: your client_id
      identityProviderConfigName: example
      issuerUrl: your issuer_url

---

