apiVersion: route53resolver.aws.jet.crossplane.io/v1alpha1
kind: QueryLogConfig
metadata:
  annotations:
    meta.upbound.io/example-id: route53resolver/v1alpha1/querylogconfig
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    destinationArn: ${aws_s3_bucket.example.arn}
    name: example
    tags:
      Environment: Prod

---

