apiVersion: elasticache.aws.jet.crossplane.io/v1alpha2
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: elasticache/v1alpha2/cluster
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    engine: memcached
    nodeType: cache.m4.large
    numCacheNodes: 2
    parameterGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    port: 11211

---

