apiVersion: elasticache.aws.jet.crossplane.io/v1alpha2
kind: ParameterGroup
metadata:
  annotations:
    meta.upbound.io/example-id: elasticache/v1alpha2/parametergroup
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    family: redis2.8
    parameter:
    - name: activerehashing
      value: "yes"
    - name: min-slaves-to-write
      value: "2"

---

