apiVersion: elasticache.aws.jet.crossplane.io/v1alpha2
kind: SubnetGroup
metadata:
  annotations:
    meta.upbound.io/example-id: elasticache/v1alpha2/subnetgroup
  labels:
    testing.upbound.io/example-name: bar
  name: bar
spec:
  forProvider:
    subnetIdsRefs:
    - name: foo

---

apiVersion: ec2.aws.jet.crossplane.io/v1alpha2
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: elasticache/v1alpha2/subnetgroup
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    availabilityZone: us-west-2a
    cidrBlock: 10.0.0.0/24
    tags:
      Name: tf-test
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo

---

apiVersion: ec2.aws.jet.crossplane.io/v1alpha2
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: elasticache/v1alpha2/subnetgroup
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    tags:
      Name: tf-test

---

