apiVersion: elasticache.aws.jet.crossplane.io/v1alpha2
kind: UserGroup
metadata:
  annotations:
    meta.upbound.io/example-id: elasticache/v1alpha2/usergroup
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    engine: REDIS
    userIdsRefs:
    - name: test

---

apiVersion: elasticache.aws.jet.crossplane.io/v1alpha2
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: elasticache/v1alpha2/usergroup
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    accessString: on ~app::* -@all +@read +@hash +@bitmap +@geo -setbit -bitfield
      -hset -hsetnx -hmset -hincrby -hincrbyfloat -hdel -bitop -geoadd -georadius
      -georadiusbymember
    engine: REDIS
    passwordsSecretRef:
    - key: example-key
      name: example-secret
      namespace: upbound-system
    userName: default

---

