apiVersion: neptune.aws.jet.crossplane.io/v1alpha2
kind: ClusterSnapshot
metadata:
  annotations:
    meta.upbound.io/example-id: neptune/v1alpha2/clustersnapshot
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    dbClusterIdentifierSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

