apiVersion: neptune.aws.jet.crossplane.io/v1alpha2
kind: ClusterInstance
metadata:
  annotations:
    meta.upbound.io/example-id: neptune/v1alpha2/clusterinstance
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    applyImmediately: true
    clusterIdentifierSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    count: 2
    engine: neptune
    instanceClass: db.r4.large

---

apiVersion: neptune.aws.jet.crossplane.io/v1alpha2
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: neptune/v1alpha2/clusterinstance
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    applyImmediately: true
    backupRetentionPeriod: 5
    engine: neptune
    iamDatabaseAuthenticationEnabled: true
    preferredBackupWindow: 07:00-09:00
    skipFinalSnapshot: true

---

