apiVersion: ecr.aws.jet.crossplane.io/v1alpha2
kind: Repository
metadata:
  annotations:
    meta.upbound.io/example-id: ecr/v1alpha2/repository
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    imageScanningConfiguration:
    - scanOnPush: true
    imageTagMutability: MUTABLE

---

