apiVersion: grafana.aws.jet.crossplane.io/v1alpha2
kind: RoleAssociation
metadata:
  annotations:
    meta.upbound.io/example-id: grafana/v1alpha2/roleassociation
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    role: ADMIN
    userIds:
    - USER_ID_1
    - USER_ID_2
    workspaceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: grafana.aws.jet.crossplane.io/v1alpha2
kind: Workspace
metadata:
  annotations:
    meta.upbound.io/example-id: grafana/v1alpha2/roleassociation
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    accountAccessType: CURRENT_ACCOUNT
    authenticationProviders:
    - SAML
    permissionType: SERVICE_MANAGED
    roleArnSelector:
      matchLabels:
        testing.upbound.io/example-name: assume

---

apiVersion: iam.aws.jet.crossplane.io/v1alpha2
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: grafana/v1alpha2/roleassociation
  labels:
    testing.upbound.io/example-name: assume
  name: assume
spec:
  forProvider:
    assumeRolePolicy: |-
      ${jsonencode({
          Version = "2012-10-17"
          Statement = [
            {
              Action = "sts:AssumeRole"
              Effect = "Allow"
              Sid    = ""
              Principal = {
                Service = "grafana.amazonaws.com"
              }
            },
          ]
        })}

---

