apiVersion: amp.aws.jet.crossplane.io/v1alpha2
kind: RuleGroupNamespace
metadata:
  annotations:
    meta.upbound.io/example-id: amp/v1alpha2/rulegroupnamespace
  labels:
    testing.upbound.io/example-name: demo
  name: demo
spec:
  forProvider:
    data: |
      groups:
        - name: test
          rules:
          - record: metric:recording_rule
            expr: avg(rate(container_cpu_usage_seconds_total[5m]))
    name: rules
    workspaceId: ${aws_prometheus_workspace.demo.id}

---

apiVersion: amp.aws.jet.crossplane.io/v1alpha2
kind: Workspace
metadata:
  annotations:
    meta.upbound.io/example-id: amp/v1alpha2/rulegroupnamespace
  labels:
    testing.upbound.io/example-name: demo
  name: demo
spec:
  forProvider: {}

---

